---
title: "Resume"
---

# **Skills**

-   Semi-fluent in Spanish                                - Excellent team player

-   Cheerful and energetic                                - Punctual and regular

-   Self-sufficient                                         - Approachable & positive attitude

-   Honest and reliable                                   - Active listener & organized

-   Manage time well

# **Experience**

**Ojai Valley Inn Hotel & Spa  (Hostess)      Ojai, Ca**                                                                               

**11/2019-2021**

-   Assisting guests to their tables

-   Bussing, sanitizing, and disinfecting tables 

-   Calling and confirming reservations

-   Creating reservations

-   Directing guests around the property

-   Taking to-go orders

\

**Immigrant Son Café (Server)        Ventura, Ca**  

**8/2021- 5/2023**

-   Serving drinks

-   Serving meals

-   Taking orders for guests

-   Assisting guests with take out orders

-   Bussing, sanitizing and disinfecting tables

\

**Trader Joe’s (Crew Member)        Ventura, Ca**  

**8/2022- 5/2023**

-   Unpack and restock items in freezers, refrigerators and unrefrigerated aisles

-   Assisting customers at the register

-   Serving free food samples to customers

-   Cleaning and sanitizing restrooms, break rooms and employee equipment

```{=html}
<!-- -->
```
-   Answering phone calls for product status and holds

\

**Embedded Statistics Tutor        Moorpark, Ca**

**8/2022 - 5/2023**

-   Created practice tests and quizzes for students

-   Dedicated 4 hours per week for office hours to answer questions and concerns

-   Held two weekly review sessions 

-   Made interactive slides and games for students to participate

\

**Woodranch BBQ and Grill (Server)        Ventura, Ca**  

**8/2023- Present**

-   Serving drinks

-   Serving meals

-   Taking orders for guests

-   Assisting guests with gift cards and promotions

# **Education**

## August 2019 - December 2021

### **Ventura College** 

-   <div>

    ### Associate in Arts: Social and Behavioral Science High Honors 

    </div>

-   <div>

    ### Associate in Arts: Mathematics

    </div>

## August 2023 - Present

### **CSU Channel Islands University** 

### Classes taken: 

-   <div>

    ### General Physics 1 (B)

    </div>

\

-   <div>

    ### Medical Anthropology (A-) 

    </div>

-   Math Junior Seminar (A+)

-   Spanish 2 (A+)

# **Research Programs and Extracurriculars**

-   Development of Language research project (Jan. 2023)

    -   Completed at University of Santa Cruz

    -   Studied the process of how language is developed through different applications such as websites, apps, television programs, movies and/or any other technological tool that focused on language learning

    -   Identified how using technology can strengthen linguistic skills and help individuals learn and retain information faster

\

-   Santa Rosa Island Research Station (Oct. 2023)

    -   Completed at CSU Channel Islands

    -   3 day 2 night astronomy trip, noted the constellations and milky way

    -   Dedicated 1 hour of community service where we picked out weeds that were an invasive species to Santa Rosa

    -   Took wellness hikes and learned about the tribal culture that took place hundreds of years ago on the island

\

-   Career Launch Program (Oct. 2023)

    -   Completed at CSU Channel Islands

    -   Club that gives us a step by step process on how any student can create relationships with professionals and land the jobs/internships they want

    -   Every Thursday from 11am-11:45am virtually

    -   In partnership with CAREER LAUNCH (A social enterprise)

\

-   California Symposium Conference (Nov. 2023)

    -   Completed at CSU Channel Islands

    -   Volunteered from 7 am to 5 pm

    -   Helped the presenters transition their slides and upload their presentations onto the screen

    -   Organized the presentations for my specific section through google slides and files

\

-   The ASSET Scholarship Program (Feb. 2024)

    -   Attend weekly meetings to discuss different scholarship opportunities

    -   Learn how to better manage scheduling conflicts and classes

    -   Build strong and meaningful connections with group members
